apiVersion: v1
kind: ConfigMap
metadata:
  name: aegisfleet-config
  namespace: aegisfleet
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: aegisfleet
  API_URL: http://api:8000/telemetry
