apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.example.yaml
  - configmap.yaml
  - postgres.yaml
  - api.yaml
  - simulator.yaml
  - prometheus.yaml
  - grafana.yaml
